2023-10-03 23:52:11,713 - ERROR - Internal Server Error: /news/news/41/delete - C:\Users\bid77\PycharmProjects\NewsPortal\venv\lib\site-packages\django\utils\log.py - (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('news_delete123.html'), <traceback object at 0x0000020F1B39A340>)
Traceback (most recent call last):
  File "C:\Users\bid77\PycharmProjects\NewsPortal\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\bid77\PycharmProjects\NewsPortal\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\bid77\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\bid77\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\bid77\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\bid77\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news_delete123.html
2023-10-03 23:52:11,718 - ERROR - "GET /news/news/41/delete HTTP/1.1" 500 89202 - C:\Users\bid77\PycharmProjects\NewsPortal\venv\lib\site-packages\django\core\servers\basehttp.py - None
